### ISSUE TITLE
I run the script but it doesnt appear in my commit history

### ISSUE THREAD

**Issue by tomassar** [isturiz/sync-graph#1]
Was this supposed to show the past commits in my history? because it doesnt.

**Comment by isturiz** [comment]
Hello, I think this should be clarified. Once you run the script, you need to push the repository to your GitHub account for the commits to be reflected in your profile. Otherwise, they will remain only as local commits.

**Comment by isturiz** [comment]
Btw, if you clone the project as a private repository, you should enable "Private contributions" on your GitHub profile.

<img width="777" alt="image" src="https://github.com/isturiz/sync-graph/assets/57846457/57b65277-3bff-4048-900b-47ecbc9a5a00">

**Comment by tomassar** [comment]
I must say this is a beautiful solution to the problem. Very straight-forward. Thanks!
