### ISSUE TITLE
Does it can help sync account work with private repo contributions to personal account ?

### ISSUE THREAD

**Issue by angushhz** [isturiz/sync-graph#2]
Related issue: https://github.com/orgs/community/discussions/23075

**Comment by angushhz** [comment]
I have setup following step :
1. Pull you code to my personal repo
2.  install pnpm  & pnpm start  & fill account github of  work (company) & yes (It show a script.sh file and i have executed it)
3. Create a repo from my personal git
4. add all file to repo
5.  push to my github
--> Result: I dont see any contributions from chart
This is my repo public: https://github.com/angushhz/sync-graph
Could it possible you to help me resolve issues with step above ?
Thank you so much ☺️

**Comment by isturiz** [comment]
Hi,

The script should contain the commits to generate, something like this:

```
GIT_COMMITTER_DATE="2024-06-25T00:00:00.000Z" git commit --allow-empty -m "Sync commit for 2024-06-25 #1" --date="2024-06-25T00:00:00.000Z"
GIT_COMMITTER_DATE="2024-06-27T00:00:00.000Z" git commit --allow-empty -m "Sync commit for 2024-06-27 #1" --date="2024-06-27T00:00:00.000Z"
GIT_COMMITTER_DATE="2024-06-27T00:00:00.000Z" git commit --allow-empty -m "Sync commit for 2024-06-27 #2" --date="2024-06-27T00:00:00.000Z"
```

If this is the case and you have executed the script correctly, you should push the repository to your personal account (angushhz).

I find step three you mentioned a bit confusing as you state in step one that you pulled my code, then you should already have a repository, there is no need to create another.

From the repository `https://github.com/isturiz/sync-graph`, you should clone it, execute the `script.sh`, and push that same repository to your GitHub account where you want the commits to be reflected, in your case, @angushhz.

The important thing is to push the `.git` directory of your repository in your GitHub. So, if I understand correctly, you are copying the `script.sh` file from one repository to another (which I would not recommend) you must execute the `script.sh` in that new repository to generate the commits in your .git directory, and push.

I hope this helps to resolve the issue. Please feel free to reach out if you encounter any further problems. 🫡

**Comment by isturiz** [comment]
Although I suppose this is not your problem, make sure to have private contributions visible in your GitHub profile settings.

see this: https://github.com/isturiz/sync-graph/issues/1#issuecomment-2207678615

**Comment by angushhz** [comment]
Wow, I don't know why yesterday i  setuped everything like above but it dont work.
But Today, I have delete everything and setup it again. And now everything from my company contribution have sync to my personal account.
It's an interesting project !  5 ⭐️
Thank you so much! I wish you the best!
